version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    depends_on:
      - application

  application:
    image: anythingthannothing/kkulog:latest
    container_name: kkulog
    restart: always
    pull_policy: always
    ports:
      - "8000:8000"
    command: ['npm', 'start']
