"use strict";
exports.__esModule = true;
var express_1 = require("express");
var admin_1 = require("./admin");
var comment_1 = require("./comment");
var post_1 = require("./post");
var user_1 = require("./user");
var upload_1 = require("./upload");
var router = (0, express_1.Router)();
router.use('/', user_1["default"]);
router.use('/admin', admin_1["default"]);
router.use('/posts', post_1["default"]);
router.use('/posts/:id/comments', comment_1["default"]);
router.use('/upload', upload_1["default"]);
exports["default"] = router;
